do $$
declare
  definition text;
begin
  select pg_get_functiondef('public.hunt_training_dummy()'::regprocedure) into definition;

  if position(E'monster_hp := greatest(0, monster_hp - damage); total_damage := total_damage + damage;' in definition) = 0
    or position(E'player_hp := greatest(0, player_hp - damage);' in definition) = 0
    or position(E'damage_result jsonb;' in definition) = 0 then
    raise exception 'hunt_training_dummy_artificial_shield_definition_unexpected';
  end if;

  definition := replace(
    definition,
    E'          damage := greatest(1, floor(raw_damage * (100.0 / (100 + monster_defense)))::integer);\n          monster_hp := greatest(0, monster_hp - damage); total_damage := total_damage + damage;\n          if player_essence_grades[index] >= 4 then player_artificial_physical_until := duration_ticks + 30; player_artificial_physical_pct := case when player_essence_grades[index] >= 5 then 8 else 5 end; end if;\n          logs := logs || jsonb_build_array(jsonb_build_object(''time_tenths'', duration_ticks, ''kind'', ''essence_cast'', ''amount'', 0, ''target_hp'', monster_hp, ''target'', ''enemy'', ''source'', ''player'', ''name'', player_essence_names[index], ''grade'', player_essence_grades[index]), jsonb_build_object(''time_tenths'', duration_ticks, ''kind'', ''essence_damage'', ''amount'', damage, ''target_hp'', monster_hp, ''target'', ''enemy'', ''source'', ''player'', ''name'', player_essence_names[index], ''grade'', player_essence_grades[index]));',
    E'          damage := greatest(1, floor(raw_damage * (100.0 / (100 + monster_defense)))::integer);\n          damage_result := public.apply_hunt_damage(monster_hp, enemy_shield, enemy_shield_until, duration_ticks, damage);\n          monster_hp := (damage_result ->> ''hp'')::numeric;\n          enemy_shield := (damage_result ->> ''shield'')::numeric;\n          shield_absorbed := (damage_result ->> ''absorbed'')::numeric;\n          damage := (damage_result ->> ''health_damage'')::integer;\n          total_damage := total_damage + damage;\n          if player_essence_grades[index] >= 4 then player_artificial_physical_until := duration_ticks + 30; player_artificial_physical_pct := case when player_essence_grades[index] >= 5 then 8 else 5 end; end if;\n          logs := logs || jsonb_build_array(jsonb_build_object(''time_tenths'', duration_ticks, ''kind'', ''essence_cast'', ''amount'', 0, ''target_hp'', monster_hp, ''target'', ''enemy'', ''source'', ''player'', ''name'', player_essence_names[index], ''grade'', player_essence_grades[index]), jsonb_build_object(''time_tenths'', duration_ticks, ''kind'', ''essence_damage'', ''amount'', damage, ''shield_absorbed'', shield_absorbed, ''target_hp'', monster_hp, ''target'', ''enemy'', ''source'', ''player'', ''name'', player_essence_names[index], ''grade'', player_essence_grades[index]));'
  );

  definition := replace(
    definition,
    E'          damage := greatest(1, floor(raw_damage * (100.0 / (100 + monster_magic_defense)))::integer);\n          monster_hp := greatest(0, monster_hp - damage); total_damage := total_damage + damage;\n          if player_essence_grades[index] >= 4 then player_artificial_magic_until := duration_ticks + 30; player_artificial_magic_pct := case when player_essence_grades[index] >= 5 then 8 else 5 end; end if;\n          logs := logs || jsonb_build_array(jsonb_build_object(''time_tenths'', duration_ticks, ''kind'', ''essence_cast'', ''amount'', 0, ''target_hp'', monster_hp, ''target'', ''enemy'', ''source'', ''player'', ''name'', player_essence_names[index], ''grade'', player_essence_grades[index]), jsonb_build_object(''time_tenths'', duration_ticks, ''kind'', ''essence_damage'', ''amount'', damage, ''target_hp'', monster_hp, ''target'', ''enemy'', ''source'', ''player'', ''name'', player_essence_names[index], ''grade'', player_essence_grades[index]));',
    E'          damage := greatest(1, floor(raw_damage * (100.0 / (100 + monster_magic_defense)))::integer);\n          damage_result := public.apply_hunt_damage(monster_hp, enemy_shield, enemy_shield_until, duration_ticks, damage);\n          monster_hp := (damage_result ->> ''hp'')::numeric;\n          enemy_shield := (damage_result ->> ''shield'')::numeric;\n          shield_absorbed := (damage_result ->> ''absorbed'')::numeric;\n          damage := (damage_result ->> ''health_damage'')::integer;\n          total_damage := total_damage + damage;\n          if player_essence_grades[index] >= 4 then player_artificial_magic_until := duration_ticks + 30; player_artificial_magic_pct := case when player_essence_grades[index] >= 5 then 8 else 5 end; end if;\n          logs := logs || jsonb_build_array(jsonb_build_object(''time_tenths'', duration_ticks, ''kind'', ''essence_cast'', ''amount'', 0, ''target_hp'', monster_hp, ''target'', ''enemy'', ''source'', ''player'', ''name'', player_essence_names[index], ''grade'', player_essence_grades[index]), jsonb_build_object(''time_tenths'', duration_ticks, ''kind'', ''essence_damage'', ''amount'', damage, ''shield_absorbed'', shield_absorbed, ''target_hp'', monster_hp, ''target'', ''enemy'', ''source'', ''player'', ''name'', player_essence_names[index], ''grade'', player_essence_grades[index]));'
  );

  definition := replace(
    definition,
    E'        damage := greatest(1, floor(raw_damage * (100 / (100 + player_defense)))::integer);\n        player_hp := greatest(0, player_hp - damage);\n        if enemy_essence_grade >= 4 then enemy_artificial_physical_until := duration_ticks + 30; enemy_artificial_physical_pct := case when enemy_essence_grade >= 5 then 8 else 5 end; end if;\n        logs := logs || jsonb_build_array(jsonb_build_object(''time_tenths'', duration_ticks, ''kind'', ''essence_cast'', ''amount'', 0, ''target_hp'', player_hp, ''target'', ''player'', ''source'', ''enemy'', ''name'', enemy_essence_name, ''grade'', enemy_essence_grade), jsonb_build_object(''time_tenths'', duration_ticks, ''kind'', ''essence_damage'', ''amount'', damage, ''target_hp'', player_hp, ''target'', ''player'', ''source'', ''enemy'', ''name'', enemy_essence_name, ''grade'', enemy_essence_grade));',
    E'        damage := greatest(1, floor(raw_damage * (100 / (100 + player_defense)))::integer);\n        damage_result := public.apply_hunt_damage(player_hp, player_shield, player_shield_until, duration_ticks, damage);\n        player_hp := (damage_result ->> ''hp'')::numeric;\n        player_shield := (damage_result ->> ''shield'')::numeric;\n        shield_absorbed := (damage_result ->> ''absorbed'')::numeric;\n        damage := (damage_result ->> ''health_damage'')::integer;\n        if enemy_essence_grade >= 4 then enemy_artificial_physical_until := duration_ticks + 30; enemy_artificial_physical_pct := case when enemy_essence_grade >= 5 then 8 else 5 end; end if;\n        logs := logs || jsonb_build_array(jsonb_build_object(''time_tenths'', duration_ticks, ''kind'', ''essence_cast'', ''amount'', 0, ''target_hp'', player_hp, ''target'', ''player'', ''source'', ''enemy'', ''name'', enemy_essence_name, ''grade'', enemy_essence_grade), jsonb_build_object(''time_tenths'', duration_ticks, ''kind'', ''essence_damage'', ''amount'', damage, ''shield_absorbed'', shield_absorbed, ''target_hp'', player_hp, ''target'', ''player'', ''source'', ''enemy'', ''name'', enemy_essence_name, ''grade'', enemy_essence_grade));'
  );

  definition := replace(
    definition,
    E'        damage := greatest(1, floor(raw_damage * (100 / (100 + player_defense)))::integer);\n        player_hp := greatest(0, player_hp - damage);\n        if enemy_essence_grade >= 4 then enemy_artificial_magic_until := duration_ticks + 30; enemy_artificial_magic_pct := case when enemy_essence_grade >= 5 then 8 else 5 end; end if;\n        logs := logs || jsonb_build_array(jsonb_build_object(''time_tenths'', duration_ticks, ''kind'', ''essence_cast'', ''amount'', 0, ''target_hp'', player_hp, ''target'', ''player'', ''source'', ''enemy'', ''name'', enemy_essence_name, ''grade'', enemy_essence_grade), jsonb_build_object(''time_tenths'', duration_ticks, ''kind'', ''essence_damage'', ''amount'', damage, ''target_hp'', player_hp, ''target'', ''player'', ''source'', ''enemy'', ''name'', enemy_essence_name, ''grade'', enemy_essence_grade));',
    E'        damage := greatest(1, floor(raw_damage * (100 / (100 + player_defense)))::integer);\n        damage_result := public.apply_hunt_damage(player_hp, player_shield, player_shield_until, duration_ticks, damage);\n        player_hp := (damage_result ->> ''hp'')::numeric;\n        player_shield := (damage_result ->> ''shield'')::numeric;\n        shield_absorbed := (damage_result ->> ''absorbed'')::numeric;\n        damage := (damage_result ->> ''health_damage'')::integer;\n        if enemy_essence_grade >= 4 then enemy_artificial_magic_until := duration_ticks + 30; enemy_artificial_magic_pct := case when enemy_essence_grade >= 5 then 8 else 5 end; end if;\n        logs := logs || jsonb_build_array(jsonb_build_object(''time_tenths'', duration_ticks, ''kind'', ''essence_cast'', ''amount'', 0, ''target_hp'', player_hp, ''target'', ''player'', ''source'', ''enemy'', ''name'', enemy_essence_name, ''grade'', enemy_essence_grade), jsonb_build_object(''time_tenths'', duration_ticks, ''kind'', ''essence_damage'', ''amount'', damage, ''shield_absorbed'', shield_absorbed, ''target_hp'', player_hp, ''target'', ''player'', ''source'', ''enemy'', ''name'', enemy_essence_name, ''grade'', enemy_essence_grade));'
  );

  if position(E'monster_hp := greatest(0, monster_hp - damage); total_damage := total_damage + damage;' in definition) > 0
    or position(E'player_hp := greatest(0, player_hp - damage);' in definition) > 0 then
    raise exception 'hunt_training_dummy_artificial_direct_damage_remains';
  end if;

  execute definition;
end;
$$;
